<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Fri, 29 May 2020 18:46:41 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: __MINIKUBE_IP__ [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */
//$cfg['PmaAbsoluteUri'] = 'http://__MINIKUBE_IP__/phpmyadmin'; 
$cfg['blowfish_secret'] = 'J=[:fP<1.A;"L]u!43(k?<VNP[:C<O-R';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>